name: Pytest

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
        django-version: ['4.2', '5.0', '5.1', '5.2']
        exclude:
          - python-version: '3.9'
            django-version: '5.0'
          - python-version: '3.9'
            django-version: '5.1'
          - python-version: '3.9'
            django-version: '5.2'
          - python-version: '3.13'
            django-version: '5.0'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package with dev dependencies
        run: |
          pip install -e ".[test]"
          pip install "Django~=${{ matrix.django-version }}"
      - name: Run tests
        run: |
          if find . -name "test_*.py" -o -name "*_test.py" | grep -q .; then
              pytest
              echo "Tests found. Running pytest."
          else
              echo "No test files found, skipping pytest"
          fi

  coverage:
    runs-on: ubuntu-latest
    needs: test  # Only runs if all tests pass
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install package with dev dependencies
        run: |
          pip install -e ".[test]"
          pip install "Django~=5.2"
      - name: Run tests with coverage
        run: |
          if find . -name "test_*.py" -o -name "*_test.py" | grep -q .; then
              pytest --cov=wt_templatetags --cov-branch --cov-report=xml
          else
              echo '<?xml version="1.0" ?><coverage></coverage>' > coverage.xml
          fi
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
