name: Pytest

on:
  push:
    branches:
      - "master"
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
        django-version: ['4.2', '5.0', '5.1', '5.2']
        exclude:
          # Django 5.x doesn't support Python 3.9
          - python-version: '3.9'
            django-version: '5.0'
          - python-version: '3.9'
            django-version: '5.1'
          - python-version: '3.9'
            django-version: '5.2'
          # Django 5.0 doesn't support Python 3.13
          - python-version: '3.13'
            django-version: '5.0'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package with dev dependencies
        run: |
          pip install -e ".[test]"
          pip install "Django~=${{ matrix.django-version }}"
      - name: Run tests and collect coverage
        run: |
          if find . -name "test_*.py" -o -name "*_test.py" | grep -q .; then
              pytest --cov=wt_templatetags --cov-branch --cov-report=xml
              echo "Tests found. Running pytest."
          else
              echo "No test files found, skipping pytest"
              echo '<?xml version="1.0" ?><coverage></coverage>' > coverage.xml
          fi
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
